version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry add codecov==2.1.10
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Extract and compile messages
          command: |
            poetry run pybabel extract -F ./babel.cfg -o ./pomodoro_system/locale/messages.pot .
            poetry run pybabel compile -d ./pomodoro_system/locale
      - run:
          name: Run test suite and linting validation
          command: |
            poetry run pytest --cov-report=html:coverage_html --cov=./
            poetry run black ./ --check
            poetry run isort ./ --check-only
            poetry run flake8 ./
      - run:
          command: poetry run codecov --token=$CODECOV_TOKEN

workflows:
  version: 2

  build-and-test-workflow:
    jobs:
      - build-and-test
